### ISSUE TITLE
Can't xyz plot a list of checkpoint names

### ISSUE THREAD

**Issue by alessandroperilli** [talesofai/comfyui-browser#33]
I have this setup:

<img width="794" alt="Screenshot 2024-04-22 at 09 44 47" src="https://github.com/talesofai/comfyui-browser/assets/9775949/e34a461e-d3e6-42a0-8ef9-8e27787ec528">

The intention is to generate an XYZ plot that modifies the checkpoint name in the `SDParameterGenerator` node, part of the` SD Prompt Reader` suite. But I also tried doing the same with an `Efficient Loader` node.

<img width="369" alt="Screenshot 2024-04-22 at 09 49 30" src="https://github.com/talesofai/comfyui-browser/assets/9775949/1165e96d-10fa-44dc-a296-e3f15f04087b">

I receive this error:

> Traceback (most recent call last):
>   File "D:\Tools\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\Tools\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\Tools\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\Tools\ComfyUI\custom_nodes\comfyui-browser\nodes\select_inputs.py", line 39, in run
>     node_id, node_title, widget_name = input.split("::")
> ValueError: not enough values to unpack (expected 3, got 1)

I thought that perhaps I'm defining the list of checkpoints in the wrong way. 

I use Vivaldi browser (a flavor of Chrome) on macOS to connect to a local ComfyUI server on Windows. 
The checkpoints are in the Windows fileserver.

Any help would be greatly appreciated. Thank you.

**Comment by alessandroperilli** [comment]
Thanks for checking. As I said, I am encountering the error also with the Efficient Loader:

<img width="544" alt="Screenshot 2024-04-22 at 16 35 08" src="https://github.com/talesofai/comfyui-browser/assets/9775949/d27e22c8-d88a-410b-9c78-784e75c16f41">

Is there any chance you can test this particular scenario?

And, regardless, what does the error mean? What is the node missing?
